const gridCells = {
    "cell_0": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAADdJREFUWIXt0LERADAMAjHWNQN6vozhFPqGllOm3SS52tO+OHEaAQIECBAgQIAAAQIECBAgMO0+fxU+YTvamioAAAAASUVORK5CYII=",
    "cell_-1": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACFJREFUOI1jyMzK2sbAwMBALk0RoIohoy4YdcGoC6jkAgBeFx8xtUdkdwAAAABJRU5ErkJggg==",
    "cell_-2": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAC5JREFUOI3tzjERAAAMwsDYLQKrryKgG7+wcWGkBUht1MtpVAt9LfS10NdC30h7JQwm/cPxhTMAAAAASUVORK5CYII=",
    "cell_-3": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACFJREFUOI1jyMzK2sbAwMBALk0RoIohoy4YdcGoC6jkAgBeFx8xtUdkdwAAAABJRU5ErkJggg==",
    "cell_-4": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAANCAYAAABy6+R8AAAAAXNSR0IArs4c6QAAABxJREFUKJFjyMzK2sbAwMBAKk17MGrTqE2YNgEAh5QZWJnuAMAAAAAASUVORK5CYII=",
    "cell_-5": "",
    "cell_-6": "",
    "cell_-7": "",
}

export default gridCells;